### ISSUE TITLE
at command ".restart" 

### ISSUE THREAD

**Issue by Ashborns** [AyGemuy/Taylor-V2#19]
pas command .restart bot nya ngelooping, restart terus.

**Comment by AyGemuy** [comment]
Iya sih, fix aj, gw gapernah make itu. Sekali pke loop pesan.

**Comment by Ashborns** [comment]
> Iya sih, fix aj, gw gapernah make itu. Sekali pke loop pesan.

+ pas add new plugin itu engga bisa auto pasang kah, harus on/off in bot nya dlu..?

**Comment by AyGemuy** [comment]
> > Iya sih, fix aj, gw gapernah make itu. Sekali pke loop pesan.
> 
> * pas add new plugin itu engga bisa auto pasang kah, harus on/off in bot nya dlu..?

Udah bisa, tadi ku coba di panel

**Comment by Ashborns** [comment]
> > > Iya sih, fix aj, gw gapernah make itu. Sekali pke loop pesan.
> > 
> > 
> > 
> > * pas add new plugin itu engga bisa auto pasang kah, harus on/off in bot nya dlu..?
> 
> Udah bisa, tadi ku coba di panel

oh, yang sekarang di update dah bisa kah?

ku kira perubahan di readme doang :v

**Comment by AyGemuy** [comment]
> > > > Iya sih, fix aj, gw gapernah make itu. Sekali pke loop pesan.
> > > 
> > > 
> > > 
> > > * pas add new plugin itu engga bisa auto pasang kah, harus on/off in bot nya dlu..?
> > 
> > 
> > Udah bisa, tadi ku coba di panel
> 
> oh, yang sekarang di update dah bisa kah?
> 
> ku kira perubahan di readme doang :v

Liat tanggal aja sih smua masih baru tuh.
