### ISSUE TITLE
Package nya kosong bg, gabisa install module

### ISSUE THREAD

**Issue by LasDrak** [AyGemuy/Taylor-V2#3]
Package nya kosong bg, gabisa install module

_Originally posted by @LasDrak in https://github.com/AyGemuy/Taylor-V2/issues/1#issuecomment-2141453293_

**Comment by AyGemuy** [comment]
> Package nya kosong bg, gabisa install module
> 
> _Originally posted by @LasDrak in [#1 (comment)](https://github.com/AyGemuy/Taylor-V2/issues/1#issuecomment-2141453293)_

Yg bner aj, Silahkan buy 1 miliyar dollar.

**Comment by LasDrak** [comment]
> > Package nya kosong bg, gabisa install module
> > 
> > _Originally posted by @LasDrak in [#1 (comment)](https://github.com/AyGemuy/Taylor-V2/issues/1#issuecomment-2141453293)_
> 
> Yg bner aj, Silahkan buy 1 miliyar dollar.
jir

**Comment by LasDrak** [comment]
anu bg, button list bisa dipakein highlight label ga?

**Comment by LasDrak** [comment]
> > Package nya kosong bg, gabisa install module
> > 
> > _Originally posted by @LasDrak in [#1 (comment)](https://github.com/AyGemuy/Taylor-V2/issues/1#issuecomment-2141453293)_
> 
> Yg bner aj, Silahkan buy 1 miliyar dollar.

maksud aku dependeciesnya

**Comment by AyGemuy** [comment]
Yawdah sih wir
