### ISSUE TITLE
Susah benr run nya🗿

### ISSUE THREAD

**Issue by VarzZX** [AyGemuy/Taylor-V2#6]

**Comment by AyGemuy** [comment]
Kenapa harus yang mudah 🗿

**Comment by VarzZX** [comment]
Sup panel ga si, ori no edit ny pun error pas run🗿

**Comment by AyGemuy** [comment]
> Sup panel ga si, ori no edit ny pun error pas run🗿

Lah gw runnya di panel harga 10k ribu itu le 🗿

**Comment by VarzZX** [comment]
Gw beres instal module lgsg off ndiri panel ny🗿

**Comment by AyGemuy** [comment]
Cona langi le, :)

**Comment by VarzZX** [comment]
Ape bende tu

**Comment by AyGemuy** [comment]
> Ape bende tu

Manuk

**Comment by eabdalmufid** [comment]
> Sup panel ga si, ori no edit ny pun error pas run🗿

Mending pake vps 15k

**Comment by AyGemuy** [comment]
> > Sup panel ga si, ori no edit ny pun error pas run🗿
> 
> Mending pake vps 15k

Gacorr king.
