### ISSUE TITLE
Abott

### ISSUE THREAD

**Issue by AliyulManan123** [AyGemuy/Taylor-V2#9]
Sc nya berat bet

**Comment by AyGemuy** [comment]
> Sc nya berat bet

Berat sama dipikul,
Anjing yang dipukul.
😹🗿

**Comment by AliyulManan123** [comment]
> > Sc nya berat bet
> 
> Berat sama dipikul, Anjing yang dipukul. 😹🗿

Woilah tutor biar nggk berat pdhal run di panel ram 2 gebe

**Comment by AliyulManan123** [comment]
Sering mati sendiri gara gara ramnya melampaui batas, pemakaian standby aja 1gb lebih ram yg digunain

**Comment by AyGemuy** [comment]
> > > Sc nya berat bet
> > 
> > 
> > Berat sama dipikul, Anjing yang dipukul. 😹🗿
> 
> Woilah tutor biar nggk berat pdhal run di panel ram 2 gebe

Apesal minim 4gb disk 4ram

**Comment by AyGemuy** [comment]
intinya diatas optiklink free

**Comment by AliyulManan123** [comment]
> > > > Sc nya berat bet
> > > 
> > > 
> > > Berat sama dipikul, Anjing yang dipukul. 😹🗿
> > 
> > 
> > Woilah tutor biar nggk berat pdhal run di panel ram 2 gebe
> 
> Apesal minim 4gb disk 4ram

Mane ada kmren di group house bot cmn 500an mb kuat

**Comment by AyGemuy** [comment]
Yawdah sih wir,
Kira kira knp tuh.
Ketebak

**Comment by AliyulManan123** [comment]
> Yawdah sih wir, Kira kira knp tuh. Ketebak

Gini amat punya admin github
